version: '3.8'

services:
  api-server:
    build: .
    image: k49api-test:latest
    restart: always
    ports:
      - "8339:8000"
    environment:
      - REDIS_URL=redis://redis-broker:6379
    depends_on:
      - redis-broker
    command: uvicorn src.api:app --host 0.0.0.0 --port 8000

  redis-broker:
    image: redis:alpine

  model-worker:
    image: k49api-test:latest
    restart: always
    environment:
      - REDIS_URL=redis://redis-broker:6379
    depends_on:
      - redis-broker
    command: python -m src.worker 
