version: '3.8'

services:
  k49api-server:
    image: mikulab/k49-api:latest
    restart: always
    container_name: k49api-server
    ports:
      - "8339:8000"
    environment:
      - REDIS_URL=redis://k49api-redis:6379
    depends_on:
      - k49api-redis
    command: uvicorn src.api:app --host 0.0.0.0 --port 8000

  k49api-redis:
    image: redis:alpine
    container_name: k49api-redis

  k49api-worker:
    image: mikulab/k49-api:latest
    container_name: k49api-worker
    restart: always
    environment:
      - REDIS_URL=redis://k49api-redis:6379
    depends_on:
      - k49api-redis
    command: python -m src.worker